manala:
  repository: "https://github.com/loic-roux-404/manala-recipes.git"
  recipe: dev.cpp

gitignore: ""

semantic_release:
  exec: { publishCmd: SKIP_EXEC=true make }
  github: { assets: [{ path: build/c-power4 }] }
