name: Package a binary

on: [push]

jobs:
    artifact:
        strategy:
            matrix:
                os: [ unbuntu-latest, macos-latest, windows-latest ]

        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: SKIP_EXEC=true make
