name: Package a binary

on: [push]
# TODO cache
jobs:
    ubuntu:
        name: Build ubuntu
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Linux tooling
              run: curl -fL wget -O - https://apt.llvm.org/llvm.sh | sudo bash

            - run: make
              env: { SKIP_EXEC: true }

            - name: Linux mac os binary
              uses: actions/upload-artifact@v2
              with:
                name: linux_binary
                path: build/c-power4-*

    macos:
        runs-on: macos-latest
        name: Build macos
        steps:
            - uses: actions/checkout@v2

            - name: Xcode tooling
              uses: maxim-lobanov/setup-xcode@v1
              with:
                xcode-version: latest-stable

            - run: make
              env: { SKIP_EXEC: true }

            - name: Store mac os binary
              uses: actions/upload-artifact@v2
              with:
                name: macos_binary
                path: build/c-power4-*

    windows:
        runs-on: windows-latest
        name: Build windows
        steps:
            - uses: actions/checkout@v2
            - uses: msys2/setup-msys2@v2
              with:
                install: make mingw-w64-x86_64-clang findutils
                path-type: minimal

            - shell: msys2 {0}
              run: make
              env: { SKIP_EXEC: true }

            - name: Windows binary
              uses: actions/upload-artifact@v2
              with:
                name: windows_binary
                path: build/c-power4-*
