name: Bump version and release

on:
    push:
        branches:
            - 'develop'
            - 'master'

jobs:
    artifact:
        strategy:
            matrix:
                java: [ 13 ]
        env:
            MVN_FLAGS: "-Dproperties.java.version=${{ matrix.java }} -B clean"

        name: Publish - GitHub Packages
        if: >
            contains(github.event.head_commit.message, '[skip-release]') == false
            && contains(github.event.pull_request.labels.*.name, 'skip-release') == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: log commit in common
              run: |
                git fetch origin
                [[ $(git rev-parse --verify HEAD) = $(git rev-parse --verify origin/develop) ]] \
                 && echo 'History OK' && exit 0 || echo "history don't match with pre-release" && exit 1
            # Install sem release plugins
            - uses: actions/setup-node@v2
            - run: |
                mkdir -p $HOME/.npm && npm config set prefix $HOME/.npm
                npm install -g \
                  "@semantic-release/changelog@^5.0.1" \
                  "@semantic-release/commit-analyzer@^8.0.1" \
                  "@semantic-release/github@^7.2.0" \
                  "@semantic-release/release-notes-generator@^9.0.1" \
                  "semantic-release@^17.3.9"

            - uses: go-semantic-release/action@v1
              with:
                prerelease: ${{ github.ref == 'refs/heads/develop' }}
                github-token: ${{ secrets.GH_TOKEN }}

            - name: Build
              run: SKIP_EXEC=true make

            - name: Upload Release Asset
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ github.event.release.upload_url }}
                asset_path: ./build/a.out
                asset_name: power4
                asset_content_type: application/octet-stream
